services:
  photo-compressor:
    build: .
    container_name: photo-compressor
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - /mnt/photo-disk/compression-data:/data
    restart: unless-stopped
